version: '3.1'

services:
  db:
    image: mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 'password123'
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -ppassword123"]
      interval: 10s
      retries: 5
      start_period: 30s

  init_db:
    build:
      context: .
      dockerfile: init_db/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 'password123'
      MYSQL_ROOT_USER: 'root'
      MYSQL_HOST: 'db'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mysql_network

  mysql_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports: 
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      init_db:
        condition: service_completed_successfully
    networks:
      - mysql_network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8000/status"]
      interval: 10s
      retries: 5
      start_period: 30s

  import_data:
    build:
      context: .
      dockerfile: import_data/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 'password123'
      MYSQL_ROOT_USER: 'root'
      MYSQL_HOST: 'db'
      COMP_PATH: '/app/scraping'
    depends_on:
      db:
        condition: service_healthy
      mysql_api:
        condition: service_healthy
    networks:
      - mysql_network

  visualizations:
    build:
      context: .
      dockerfile: visualizations/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 'password123'
      MYSQL_HOST: 'db'
    depends_on:
      import_data:
        condition: service_completed_successfully
    ports:
      - "8501:8501"
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
